//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int IdPatient { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public int Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string CC_BI { get; set; }
        public int SNS { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string Allergies { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<int> OtherContact { get; set; }
    }
}
