//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFMedacService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int Id { get; set; }
        public Nullable<int> BloodPressureMin { get; set; }
        public Nullable<int> BloodPressureMax { get; set; }
        public Nullable<int> HeartRate { get; set; }
        public Nullable<int> OxygenSaturation { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public int FK_SNS { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
